icoo_pitanja_route_hr:
    pattern:  /{_locale}/najcesca-pitanja
    defaults: { _controller: IcooPitanjaBundle:Pitanja:pitanja, _locale:hr }
    requirements:
        _locale: hr|en|de

icoo_pitanja_route_en:
    pattern:  /{_locale}/common-questions
    defaults: { _controller: IcooPitanjaBundle:Pitanja:pitanja, _locale:en }
    requirements:
        _locale: hr|en|de
