parameters:
#    icoo_pitanja.example.class: Icoo\PitanjaBundle\Example

services:
#    icoo_pitanja.example:
#        class: %icoo_pitanja.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
