parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     icoo
    database_user:     root
    database_password: 

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            $2y$10$JDEkcUovLnJSMi4kYUk1M.TCoyA.e10DWH8nb4Klc1FuDg9qZZlS6
