Icoo\UpitBundle\Entity\UpitEntity:
    properties:
        ime : 
            - NotBlank : { message : "upitentity.ime.not_blank"}
            - Length : 
                max : 100
                maxMessage : "upitentity.ime.length"
        email :
            - NotBlank : { message : "upitentity.email.not_blank"}
            - Email: { message: "upitentity.email.email" }
        upit : 
            - Length : 
                max : 5000
                maxMessage: "upitentity.upit.length"