icoo_potrebe_projekta_route:
    pattern:  /{_locale}/potrebe-projekta
    defaults: { _controller: IcooPotrebeProjektaBundle:PotrebeProjekta:potrebeProjekta, _locale:hr }
    requirements:
        _locale: hr|en|de
