parameters:
#    icoo_djelatnost.example.class: Icoo\DjelatnostBundle\Example

services:
#    icoo_djelatnost.example:
#        class: %icoo_djelatnost.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
